services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      macvlan_net:
        ipv4_address: ${ip_address}
    mac_address: ${mac_address}
    cap_drop:
      - ALL
    cap_add:
      - CAP_CHOWN
      - CAP_NET_BIND_SERVICE
      - CAP_NET_RAW
    #read_only: true
    #tmpfs:
    #  - /tmp
    #  - /var/log
    volumes:
      - pihole_config:/etc/pihole
      - dnsmasq_config:/etc/dnsmasq.d
    environment:
      TZ: ${TIMEZONE}
      WEBPASSWORD: ${WEBPASSWORD}
      DNSMASQ_USER: ${DNSMASQ_USER}
      PIHOLE_UID: ${PIHOLE_UID}
      PIHOLE_GID: ${PIHOLE_GID}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "dig", "@127.0.0.1", "pi.hole"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  macvlan_net:
    driver: macvlan
    driver_opts:
      parent: ${macvlan_parent}
    ipam:
      config:
        - subnet: ${macvlan_subnet}
          gateway: ${macvlan_gateway}
          ip_range: ${macvlan_ip_range}

volumes:
  pihole_config:
  dnsmasq_config:
